### ISSUE TITLE
Plugin causes new file name to be overwritten

### ISSUE THREAD

**Issue by pdoak** [bogado/file-line#45]
If I launch vim from zsh with the following command `vim 2015.md`, the plugin causes a new file to be made but with the name "0" and not "2015.md".

**Comment by scmx** [comment]
I'm having the same issue

![img](http://cl.ly/image/26250n3G1B1B/Screen%20Recording%202015-04-08%20at%2010.41%20am.gif)
When I disable the plugin as shown in the gif above, it works again.
