### ISSUE TITLE
getting 'Press ENTER... to continue' messages

### ISSUE THREAD

**Issue by mulm** [bogado/file-line#46]
When file-line plugin is included, I get the 'Press ENTER... to continue' messages when opening multiple files.  Without file-line, I do not get the prompts.

**Comment by designsimply** [comment]
I'm seeing a similar problem even when opening one file. I have to hit enter one extra time when I open a file without a line number `vi .vimrc` and I have to hit enter two extra times when I try opening a file with a line number `vi .vimrc:41`. See this [short screencast](https://cloudup.com/cR1LqIvWqxp). I'm running Mac OS X Yosemite with vim 7.4 installed via homebrew.
